ModuleParams:
  IAMPermissions:
    PolicyStaements: |
      [
      ]
    ManagedPolicyArns: 
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
    TrustedServices: []
    ServiceLinkedRoles: []
    Checkpoints: []
TemplateReplace: []
ScriptFiles:
  'install-sample-1.sh': []
  'install-sample-2.sh': []
  'install-sample-3.sh': []
      