ModuleParams:
  IAMPermissions:
    PolicyStaements: |
      [
      ]
    ManagedPolicyArns: 
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
    TrustedServices: []
    ServiceLinkedRoles: []
    Checkpoints: []
TemplateReplace: []
ScriptFiles:
  'increase-disk-size.sh': 
    DiskSize: '20'
  'eks-tool-set.sh': []
  'eks-cluster.sh': 
    Eks_Version: '1.19'
    Eks_Name: eksworkshop-eksctl
    Eks_DersiredCapacity: '3'
    Eks_InstanceType: 'm5.large'
    Eks_MinSize: '1'
    Eks_MaxSize: '3'
    Eks_VolumeSize: '20'
    Eks_NG1_Name: nodegroup
  'basic-k8s-apps.sh': []
TestConfiguration: 
  LocalMarkdownServer: "https://artifacts.us-east-1.prod.workshops.aws/cli/linux/preview_build"
  WorkshopGitLocation: "/home/ec2-user/environment/worksshop-content/eksid"
  WorkshopRemoteUrl: 'https://catalog.us-east-1.prod.workshops.aws/v2/workshops/76a5dd80-3249-4101-8726-9be3eeee09b2/en-US/helm'
  #WorkshopRemoteUrl: "https://catalog.us-east-1.prod.workshops.aws/v2/workshops/76a5dd80-3249-4101-8726-9be3eeee09b2/en-US/"
  TestRemote: true