ModuleParams:
  IAMPermissions:
    PolicyStaements: |
      [
      ]
    ManagedPolicyArns: 
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
    TrustedServices: []
    ServiceLinkedRoles: []
    Checkpoints: []
TemplateReplace: []
ScriptFiles:
  'increase-disk-size.sh': 
    DiskSize: '20'
  'eks-tool-set.sh': []
  'eks-cluster.sh': 
    version: '1.16'
    name: eksworkshop-eksctl
    nodes: '2'
    node_labels: lifecycle=OnDemand,intent=control-apps
  'basic-k8s-apps.sh': []
    
      