ModuleParams:
  IAMPermissions:
    PolicyStaements: |
      [
      ]
    ManagedPolicyArns: 
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
    TrustedServices: []
    ServiceLinkedRoles: []
    Checkpoints: []
TemplateReplace: []
ScriptFiles:
  'increase-disk-size.sh': 
    DiskSize: '20'
  'eks-tool-set.sh': []
  'eks-cluster.sh': 
    Eks_Version: '1.19'
    Eks_Name: eksworkshop-eksctl
    Eks_DersiredCapacity: '3'
    Eks_InstanceType: 't3.small'
    Eks_MinSize: '1'
    Eks_MaxSize: '3'
    Eks_VolumeSize: '20'
    Eks_NG1_Name: nodegroup
  'basic-k8s-apps.sh': []
    
      